apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: auth-alerts
  namespace: monitoring
spec:
  groups:
    - name: auth-service
      rules:
        - alert: AuthServiceDown
          expr: up == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            description: "Auth service is down"