apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: gestion-projet
data:
  SERVER_PORT: "8081"
  SPRING_APPLICATION_NAME: "auth-service"

  SPRING_DATASOURCE_URL: "jdbc:postgresql://ep-wandering-rice-a4uh9a3k.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"

  HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
  HIBERNATE_FORMAT_SQL: "true"

  LOGGING_LEVEL_ROOT: "DEBUG"
  LOGGING_LEVEL_SPRING: "DEBUG"
  LOGGING_LEVEL_WEB: "DEBUG"
  LOGGING_LEVEL_SECURITY: "DEBUG"
  LOGGING_LEVEL_HIBERNATE: "DEBUG"
  LOGGING_LEVEL_SQL: "DEBUG"
  LOGGING_LEVEL_BINDER: "TRACE"
  LOGGING_LEVEL_APP: "DEBUG"

