apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: gestion-projet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: nour292/auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081

          env:
            # --- CONFIGMAP ---
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: SERVER_PORT

            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: SPRING_APPLICATION_NAME

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO

            - name: SPRING_JPA_SHOW_SQL
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: SPRING_JPA_SHOW_SQL

            - name: HIBERNATE_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: HIBERNATE_DIALECT

            - name: HIBERNATE_FORMAT_SQL
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: HIBERNATE_FORMAT_SQL

            # --- SECRET ---
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: SPRING_DATASOURCE_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET

            - name: JWT_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_EXPIRATION

            - name: JWT_REFRESH_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_REFRESH_EXPIRATION

