apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: gestion-projet
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "neondb_owner"
  SPRING_DATASOURCE_PASSWORD: "npg_Yy8UThLqaXE1"

  JWT_SECRET: "MaCleUltraSecretePourJWT256BitsSuperLongue1234567890"
  JWT_EXPIRATION: "86400000"
  JWT_REFRESH_EXPIRATION: "604800000"
